name: GitHub Actions Config
on: 
  push:
    branches: [ master ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ runner.os }}"
      - run: echo "${{ github.ref }} ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "clone complate"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "status: ${{ job.status }}"
